name: Format check
on: [pull_request]

jobs:
  format-check:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version-file: 'package.json'
          cache: 'npm'

      - name: Install Dependencies
        run: npm ci

      - name: Run Format Check
        run: npm run formatting
