name: Run LWC unit tests
on: [pull_request]

jobs:
  unit-tests:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version-file: 'package.json'
          cache: 'npm'

      - name: Install Dependencies
        run: npm ci

      - name: Run client unit tests (JS)
        run: npm run test:unit
